// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/config.proto

package config

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = types.DynamicAny{}
)

// Validate checks the field values on ServiceDefinition with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ServiceDefinition) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetVersion() != 1 {
		return ServiceDefinitionValidationError{
			field:  "Version",
			reason: "value must equal 1",
		}
	}

	if len(m.GetDependencies()) < 1 {
		return ServiceDefinitionValidationError{
			field:  "Dependencies",
			reason: "value must contain at least 1 item(s)",
		}
	}

	for idx, item := range m.GetDependencies() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServiceDefinitionValidationError{
					field:  fmt.Sprintf("Dependencies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ServiceDefinitionValidationError is the validation error returned by
// ServiceDefinition.Validate if the designated constraints aren't met.
type ServiceDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceDefinitionValidationError) ErrorName() string {
	return "ServiceDefinitionValidationError"
}

// Error satisfies the builtin error interface
func (e ServiceDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceDefinitionValidationError{}

// Validate checks the field values on Dependency with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Dependency) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		return DependencyValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetClusterName()) < 1 {
		return DependencyValidationError{
			field:  "ClusterName",
			reason: "value length must be at least 1 runes",
		}
	}

	// no validation rules for HostHeader

	if v, ok := interface{}(m.GetTls()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DependencyValidationError{
				field:  "Tls",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetConnectTimeoutMs() <= 0 {
		return DependencyValidationError{
			field:  "ConnectTimeoutMs",
			reason: "value must be greater than 0",
		}
	}

	if m.GetCircuitBreaker() == nil {
		return DependencyValidationError{
			field:  "CircuitBreaker",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetCircuitBreaker()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DependencyValidationError{
				field:  "CircuitBreaker",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetRoutes()) < 1 {
		return DependencyValidationError{
			field:  "Routes",
			reason: "value must contain at least 1 item(s)",
		}
	}

	for idx, item := range m.GetRoutes() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DependencyValidationError{
					field:  fmt.Sprintf("Routes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if v, ok := interface{}(m.GetOutlierDetection()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DependencyValidationError{
				field:  "OutlierDetection",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for HealthCheckPath

	switch m.DiscoveryOption.(type) {

	case *Dependency_Lb:
		// no validation rules for Lb

	case *Dependency_Sds:

		if v, ok := interface{}(m.GetSds()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DependencyValidationError{
					field:  "Sds",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		return DependencyValidationError{
			field:  "DiscoveryOption",
			reason: "value is required",
		}

	}

	return nil
}

// DependencyValidationError is the validation error returned by
// Dependency.Validate if the designated constraints aren't met.
type DependencyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DependencyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DependencyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DependencyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DependencyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DependencyValidationError) ErrorName() string { return "DependencyValidationError" }

// Error satisfies the builtin error interface
func (e DependencyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDependency.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DependencyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DependencyValidationError{}

// Validate checks the field values on CircuitBreaker with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CircuitBreaker) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetMaxConnections() <= 0 {
		return CircuitBreakerValidationError{
			field:  "MaxConnections",
			reason: "value must be greater than 0",
		}
	}

	if m.GetMaxPendingRequests() <= 0 {
		return CircuitBreakerValidationError{
			field:  "MaxPendingRequests",
			reason: "value must be greater than 0",
		}
	}

	if m.GetMaxRetries() <= 0 {
		return CircuitBreakerValidationError{
			field:  "MaxRetries",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// CircuitBreakerValidationError is the validation error returned by
// CircuitBreaker.Validate if the designated constraints aren't met.
type CircuitBreakerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CircuitBreakerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CircuitBreakerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CircuitBreakerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CircuitBreakerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CircuitBreakerValidationError) ErrorName() string { return "CircuitBreakerValidationError" }

// Error satisfies the builtin error interface
func (e CircuitBreakerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCircuitBreaker.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CircuitBreakerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CircuitBreakerValidationError{}

// Validate checks the field values on Route with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Route) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Method

	if m.GetTimeoutMs() <= 0 {
		return RouteValidationError{
			field:  "TimeoutMs",
			reason: "value must be greater than 0",
		}
	}

	if m.GetRetryPolicy() == nil {
		return RouteValidationError{
			field:  "RetryPolicy",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetRetryPolicy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RouteValidationError{
				field:  "RetryPolicy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch m.PathSpecifier.(type) {

	case *Route_Prefix:
		// no validation rules for Prefix

	case *Route_Path:
		// no validation rules for Path

	default:
		return RouteValidationError{
			field:  "PathSpecifier",
			reason: "value is required",
		}

	}

	return nil
}

// RouteValidationError is the validation error returned by Route.Validate if
// the designated constraints aren't met.
type RouteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RouteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RouteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RouteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RouteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RouteValidationError) ErrorName() string { return "RouteValidationError" }

// Error satisfies the builtin error interface
func (e RouteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoute.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RouteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RouteValidationError{}

// Validate checks the field values on RetryPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *RetryPolicy) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetRetryOn()) < 1 {
		return RetryPolicyValidationError{
			field:  "RetryOn",
			reason: "value length must be at least 1 runes",
		}
	}

	if m.GetNumRetries() <= 0 {
		return RetryPolicyValidationError{
			field:  "NumRetries",
			reason: "value must be greater than 0",
		}
	}

	if m.GetPerTryTimeoutMs() <= 0 {
		return RetryPolicyValidationError{
			field:  "PerTryTimeoutMs",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// RetryPolicyValidationError is the validation error returned by
// RetryPolicy.Validate if the designated constraints aren't met.
type RetryPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryPolicyValidationError) ErrorName() string { return "RetryPolicyValidationError" }

// Error satisfies the builtin error interface
func (e RetryPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryPolicyValidationError{}

// Validate checks the field values on OutlierDetection with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *OutlierDetection) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Consecutive_5Xx

	return nil
}

// OutlierDetectionValidationError is the validation error returned by
// OutlierDetection.Validate if the designated constraints aren't met.
type OutlierDetectionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OutlierDetectionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OutlierDetectionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OutlierDetectionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OutlierDetectionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OutlierDetectionValidationError) ErrorName() string { return "OutlierDetectionValidationError" }

// Error satisfies the builtin error interface
func (e OutlierDetectionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOutlierDetection.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OutlierDetectionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OutlierDetectionValidationError{}
